package constants

const (
	HTTP_REQUEST_METHOD_PUT     = "PUT"
	HTTP_REQUEST_METHOD_DELETE  = "DELETE"
	HTTP_REQUEST_METHOD_GET     = "GET"
	HTTP_REQUEST_METHOD_POST    = "POST"
	HTTP_REQUEST_METHOD_HEAD    = "HEAD"
	HTTP_REQUEST_METHOD_OPTIONS = "OPTIONS"
	HTTP_REQUEST_METHOD_TRACE   = "TRACE"
)

// for request,response header
const (
	HTTP_HEADER_KEY_CONTENT_TYPE                 = "Content-Type"
	HTTP_HEADER_KEY_CONTENT_DISPOSITION          = "Content-Disposition"
	HTTP_HEADER_KEY_ACCEPT_CHARSET               = "Accept-Charset"
	HTTP_HEADER_KEY_CONTENT_ENCODING             = "Content-Encoding"
	HTTP_HEADER_KEY_ACCESS_TOKEN                 = "Access-Token"
	HTTP_HEADER_KEY_ACCESS_CONTROL_ALLOW_ORIGIN  = "Access-Control-Allow-Origin"
	HTTP_HEADER_KEY_ACCESS_CONTROL_ALLOW_METHODS = "Access-Control-Allow-Methods"
	HTTP_HEADER_KEY_ACCESS_CONTROL_ALLOW_HEADERS = "Access-Control-Allow-Headers"
	HTTP_HEADER_KEY_ORIGIN                       = "Origin"
	HTTP_HEADER_KEY_ACCEPT                       = "Accept"
)

// for request,response content type
const (
	HTTP_CONTENT_TYPE_TEXT_PLAIN                        = "text/plain"
	HTTP_CONTENT_TYPE_APPLICATION_X_DOWNLOAD            = "application/x-download"
	HTTP_CONTENT_TYPE_APPLICATION_ANDROID_PACKAGE       = "application/vnd.android.package-archive"
	HTTP_CONTENT_TYPE_MULTIPART_FORM_DATA               = "multipart/form-data"
	HTTP_CONTENT_TYPE_APPLICATION_OCTET_STREAM          = "application/octet-stream"
	HTTP_CONTENT_TYPE_BINARY_OCTET_STREAM               = "binary/octet-stream"
	HTTP_CONTENT_TYPE_APPLICATION_X_WWW_FORM_URLENCODED = "application/x-www-form-urlencoded"
	HTTP_CONTENT_TYPE_APPLICATION_JSON                  = "application/json"
)

// http status code
const (
	HTTP_STATUS_CODE_CONTINUE                      = 100
	HTTP_STATUS_CODE_SWITCHING_PROTOCOLS           = 101
	HTTP_STATUS_CODE_PROCESSING                    = 102
	HTTP_STATUS_CODE_OK                            = 200
	HTTP_STATUS_CODE_CREATED                       = 201
	HTTP_STATUS_CODE_ACCEPTED                      = 202
	HTTP_STATUS_CODE_NON_AUTHORITATIVE_INFORMATION = 203
	HTTP_STATUS_CODE_NO_CONTENT                    = 204
	HTTP_STATUS_CODE_RESET_CONTENT                 = 205
	HTTP_STATUS_CODE_PARTIAL_CONTENT               = 206
	HTTP_STATUS_CODE_MULTI_STATUS                  = 207
	HTTP_STATUS_CODE_MULTIPLE_CHOICES              = 300
	HTTP_STATUS_CODE_MOVED_PERMANENTLY             = 301
	HTTP_STATUS_CODE_FOUND                         = 302
	HTTP_STATUS_CODE_SEE_OTHER                     = 303
	HTTP_STATUS_CODE_NOT_MODIFIED                  = 304
	HTTP_STATUS_CODE_USE_PROXY                     = 305
	HTTP_STATUS_CODE_SWITCH_PROXY                  = 306
	HTTP_STATUS_CODE_TEMPORARY_REDIRECT            = 307
	HTTP_STATUS_CODE_BAD_REQUEST                   = 400
	HTTP_STATUS_CODE_UNAUTHORIZED                  = 401
	HTTP_STATUS_CODE_PAYMENT_REQUIRED              = 402
	HTTP_STATUS_CODE_FORBIDDEN                     = 403
	HTTP_STATUS_CODE_NOT_FOUND                     = 404
	HTTP_STATUS_CODE_METHOD_NOT_ALLOWED            = 405
	HTTP_STATUS_CODE_NOT_ACCEPTABLE                = 406
	HTTP_STATUS_CODE_REQUEST_TIMEOUT               = 408
	HTTP_STATUS_CODE_CONFLICT                      = 409
	HTTP_STATUS_CODE_GONE                          = 410
	HTTP_STATUS_CODE_LENGTH_REQUIRED               = 411
	HTTP_STATUS_CODE_PRECONDITION_FAILED           = 412
	HTTP_STATUS_CODE_REQUEST_URI_TOO_LONG          = 414
	HTTP_STATUS_CODE_EXPECTATION_FAILED            = 417
	HTTP_STATUS_CODE_TOO_MANY_CONNECTIONS          = 421
	HTTP_STATUS_CODE_UNPROCESSABLE_ENTITY          = 422
	HTTP_STATUS_CODE_LOCKED                        = 423
	HTTP_STATUS_CODE_FAILED_DEPENDENCY             = 424
	HTTP_STATUS_CODE_UNORDERED_COLLECTION          = 425
	HTTP_STATUS_CODE_UPGRADE_REQUIRED              = 426
	HTTP_STATUS_CODE_RETRY_WITH                    = 449
	HTTP_STATUS_CODE_INTERNAL_SERVER_ERROR         = 500
	HTTP_STATUS_CODE_NOT_IMPLEMENTED               = 501
	HTTP_STATUS_CODE_BAD_GATEWAY                   = 502
	HTTP_STATUS_CODE_SERVICE_UNAVAILABLE           = 503
	HTTP_STATUS_CODE_GATEWAY_TIMEOUT               = 504
	HTTP_STATUS_CODE_HTTP_VERSION_NOT_SUPPORTED    = 505
	HTTP_STATUS_CODE_VARIANT_ALSO_NEGOTIATES       = 506
	HTTP_STATUS_CODE_INSUFFICIENT_STORAGE          = 507
	HTTP_STATUS_CODE_LOOP_DETECTED                 = 508
	HTTP_STATUS_CODE_BANDWIDTH_LIMIT_EXCEEDED      = 509
	HTTP_STATUS_CODE_NOT_EXTENDED                  = 510
	HTTP_STATUS_CODE_UNPARSEABLE_RESPONSE_HEADERS  = 600
)
